### ISSUE TITLE
Zotero export to openmappr 

### ISSUE THREAD

**Issue by retorquere** [vibrant-data-labs/py2mappr#1]
Let's coordinate the process of going from zotero to openmappr here.

**Comment by retorquere** [comment]
Jakob: I can only export a single file, text-based format in zotero. The only format I know that fits the nodes-and-edges format would be flat ods, but you'll have to open that in libreoffice and save to excel to feed it into py2mappr.

**Comment by Jack-613** [comment]
Hi Emile,

sorry for the delay; have just subscribed.

Best Jakob

**Comment by Jack-613** [comment]
That would be fine if you could describe to me exactly how the process works ?

**Comment by ericberlow** [comment]
Hi team -  you need to export to a csv or excel a table where every record is a citation, and the columns are the fields you have for that citation - they must include at minimum - unique id, title, abstract, keywords (or 'tags')

**Comment by retorquere** [comment]
Tags separated by a vertical bar in a single field, yes?

I can just use id, title, abstract etc as column headers?

Flat ods is a spreadsheet format, so it converts easily to excel. That will be a manual step though.

**Comment by ericberlow** [comment]
Tags: yes that's great.  Or whatever delimiter you prefer. We can fix it in the data prep script. 
Column headers:  Can be whatever you want.  They will be attribute labels in the viz - or we can rename them later.

**Comment by retorquere** [comment]
Ok, then the excel file I mailed earlier should have what we need qua structure. I can always add additional fields. I'll do that when I get home, but that's at least 3 hours away. Probably 4.

**Comment by ericberlow** [comment]
@retorquere  - just saw that excel file - the nodes sheet appears to be a list of authors (not publications), and the links sheet does not have a list of links between nodes, but is rather a bipartite network linking journal to author?  openmappr can render whatever you want, but this would not be the same as a document affinity network. You could do a co-authorship network, or a bipartite journal <> author network. In the latter case, you would need to add the journals to the nodes sheet and ideally add a categorical attribute that secifies 'journal' vs 'author' so you could color by or filter by node type.

**Comment by retorquere** [comment]
The nodes are authors and articles, the links are links between articles and authors. Urls are articles, names are authors. Not good?

**Comment by retorquere** [comment]
Can you give me a sample of such an excel sheet?

**Comment by ericberlow** [comment]
What you describe is fine if you want a network that links authors to articles.  

Here is a demo file of a document network that links articles to articles if they have similar keywords 0- which is I think what @Jack-613 is looking for?  

[NCEAS_Kwd_Network_demo.xlsx](https://github.com/ericberlow/py2mappr/files/6895969/NCEAS_Kwd_Network_demo.xlsx)
A version of this is visualized here:  https://openmappr.com/play/NCEAS_Keyword_Network

**Comment by retorquere** [comment]
@Jack-613 you can best outline what you want achieved - I think I might not have interpreted your request right.

**Comment by retorquere** [comment]
@ericberlow what do the links represent in the 2nd sheet? I can generate the first sheet of articles easily, but I do not know on what basis I should declare two articles to be related for the 2nd sheet. When I know that, and I know what to do with that Excel, I may have enough information to proceed further on my own.

@Jack-613 in the RDF file you gave me there are not sufficient keywords to generate this kind of map. I think before jumping into implementation it is of great importance to get a clearer picture of what problem is to be solved by the visualization you seek.

**Comment by ericberlow** [comment]
> @ericberlow what do the links represent in the 2nd sheet? I can generate the first sheet of articles easily, but I do not know on what basis I should declare two articles to be related for the 2nd sheet. When I know that, and I know what to do with that Excel, I may have enough information to proceed further on my own.

the links connect papers that have high similarity in keywords - this is not a py2mappr thing, but rather comes from the tag2network repo:  https://github.com/foodwebster/tag2network  which generates a similarity network based on  sparsified matrix of cosine similarity in keyword sets. 

I was under the impression that @Jack-613 wanted something similar to what we published here: https://openmappr.com/play/CreativityResearch1990-2015  

As I mentioned earlier - if you don't have enough keywords - or consistently applied keywords, it is hard to generate a good quality document similarity network.  We used Web of Science data in part because it has really rich keywords for each publication.  

You could also if you want generate a co-authorship network which links documents if they share an author like this: https://openmappr.com/play/SNARL_CoAuthorship. - or flip it and link authors if they have ever published together.

**Comment by retorquere** [comment]
This is the description I was given:

> I am thinking of a translator that will export Zotero items (Zotero collection) in a format that Openmappr can import. 
>
> To export Zotero Items and import and display them as a network with openmappr.
>
> It would be great if the articles or authors were represented as nodes. The link between the nodes would lead to the co-authors. 
>
> When clicking on the nodes, the information like title, authors, year and the PROSEC links would be displayed in the left area (like in the B example)

**Comment by ericberlow** [comment]
> This is the description I was given:
> 
> > I am thinking of a translator that will export Zotero items (Zotero collection) in a format that Openmappr can import.
> > To export Zotero Items and import and display them as a network with openmappr.
> > It would be great if the articles or authors were represented as nodes. The link between the nodes would lead to the co-authors.
> > When clicking on the nodes, the information like title, authors, year and the PROSEC links would be displayed in the left area (like in the B example)

This is the description I was given: 

"Hello Eric, my name is jakob I am a scientifically researching physician and enthusiastic about your project. I would be grateful if you could put me in contact with a programmer who would help me to visualize my publication database (zotero) as a visualization with your tool (openmappr-player) on my website ... like you did with your "25 Years of Creativity Research" sample but with my own data."     -- 

that would be this publication - https://www.tandfonline.com/doi/full/10.1080/10400419.2016.1230358 
and this map --  https://openmappr.com/play/CreativityResearch1990-2015

**Comment by retorquere** [comment]
@Jack-613, your turn I think.

**Comment by Jack-613** [comment]
Sorry for the delay and confusion, I couldn't follow your discussion properly for a while and only just realized it was my turn. 

What I have in mind is the representation of the zotero entries as network visualizations in which the collaboration of the authors becomes visible.

I thought that the nodes would be the authors (with information of their articles) and the connections to the co-authors in the network of further nodes (authors) would be represented.

I'm not sure if I could express myself in a reasonably understandable way?

**Comment by Jack-613** [comment]
I will send you another test export of Zotero entries that should also have enough TAG`s via email

**Comment by retorquere** [comment]
Github is restrictive about what you attach here but will allow anything you rename to be `.txt`, or anything in a `.zip`.

If I understand correctly, this excel should represent what you mean (attaching the source RDF for reference).
[Exported Items.rdf.txt](https://github.com/ericberlow/py2mappr/files/6898296/Exported.Items.rdf.txt)

**Comment by Jack-613** [comment]
Opened the Excel and guess it works :-)

What I was wondering if the thickness of the connecting line between the nodes could be visualized varying depending on the number of common publications ?

Example:

A+B have 10 common publications
A+C have 1 common publication 

This would cause the connecting line between A+B to be displayed much thicker than the connecting line between A+C.

What do you think ?

**Comment by retorquere** [comment]
Sure - I realize I'm duplicating edges. I'll get you a new one.

**Comment by Jack-613** [comment]
Do you have openmappr already installed on your computer ?

If so, could you please send me a sample screenshot of the network visualization ?

**Comment by retorquere** [comment]
@Jack-613 who are you addressing?

weighted edges:
[Exported Items.xlsx](https://github.com/ericberlow/py2mappr/files/6900522/Exported.Items.xlsx)

**Comment by retorquere** [comment]
If you are addressing me: 

> Do you have openmappr already installed on your computer ?

I don't know what it would mean to install openmappr? It is my understanding that p2mappr (a python script that I don't have to install) would generate a static site (which I don't have to install).

> If so, could you please send me a sample screenshot of the network visualization ?

If I knew how to do this, we wouldn't be having this conversation? I'm thoroughly confused now.

**Comment by Jack-613** [comment]
Emile, the excel looks great !

Please forgive, what I meant is the workflow from the excel to import p2mappr.

I did not want to be pushy or impatient here in any case, sorry !

**Comment by ericberlow** [comment]
@retorquere  - you are correct - py2mappr was created so you don't have to host openmappr on a server.  it is also easier to integrate into your data science pipeline in python to repeat or update the network with new data.  

I understand now that @Jack-613 is not interested in the document network - which was that creativity research synthesis - but rather a co-authorship network.  The format of the excel you just sent is perfect for a start.  Now you just need to use networkx to add network metrics to the nodes sheet - for example - degree, betweenness centrality, louvain cluster (or module), force-directed layout x and y for each node (person), etc.     In this co-author network, I'm guessing there will be alot of small isloated components and singletons - you may want to just keep the giant component (the largest fully connected network), or drop components smaller than a few people.   


Once that is done we can create a project to covert this 2-sheet excel file into py2mappr files and create a template for specifying settings etc for an openmappr player. 

Just to reiterate for @Jack-613  - openmappr is an interactive network visualizer not a network analysis tool.  Generating the network file and adding metadata to the nodes (network metrics, any other information you want to see when you click on a node, or attributes you want to use to query and select nodes) must be added prior to rendering the visualization. For example, with the current nodes sheet - a list of authors, some of which have tags - there is not much else there to position those nodes (people) in space or to color them by category, or filter them by e.g. institution, or geography, etc.  And the tags are missing for many, so you won't be able to filter them by topic. But it should identify clusters of people that tend to collaborate with one another in this document set.

**Comment by ericberlow** [comment]
@retorquere  - the TED talks network project in this repo should also have an example of creating the player snapshots and specifying all the settings for it.  In that project folder is a simple 'prepare_data.py' script to create the py2mappr nodes, links, node_attributes.csv files -  the latter will just be an empty template that you fill in manually - check the TED talks one for an example.

**Comment by Jack-613** [comment]
Thank you !

**Comment by retorquere** [comment]
> The format of the excel you just sent is perfect for a start. Now you just need to use networkx to add network metrics to the nodes sheet - for example - degree, betweenness centrality, louvain cluster (or module), force-directed layout x and y for each node (person), etc. In this co-author network, I'm guessing there will be alot of small isloated components and singletons - you may want to just keep the giant component (the largest fully connected network), or drop components smaller than a few people.

Which of these parts should I generate, and which parts will be generated by py2mappr?

BTW if the input needs to be read into networkx, I can probably more easily generate a format that networkx can read directly:

* edge list
* gexf
* GML
* GraphML
* JSON

should all be easy to generate for me

> Please forgive, what I meant is the workflow from the excel to import p2mappr.
> 
> I did not want to be pushy or impatient here in any case, sorry !

It wasn't taken that way, but I needed to know we have the same expectations for the outcome.


> the TED talks network project in this repo should also have an example of creating the player snapshots and specifying all the settings for it. In that project folder is a simple 'prepare_data.py' script to create the py2mappr nodes, links, node_attributes.csv files - the latter will just be an empty template that you fill in manually - check the TED talks one for an example.

I'll look into that.

**Comment by ericberlow** [comment]
"Which of these parts should I generate, and which parts will be generated by py2mappr?"
@retorquere - apologies if there is any confusion - py2mappr is just for visualizing what you have generated - all the data for visualizing must be pre-generated.  That basically just means adding more columns to the nodes sheet that you will use for specifying node sizes, node colors, node position in x, y space, and then any other node details that you want to be able to use for querying / selecting them (e.g. numeric, categorical, or tag filters)

**Comment by retorquere** [comment]
I thought the "force-directed layout x and y for each node (person)" was calculated by py2mappr?

**Comment by ericberlow** [comment]
> I thought the "force-directed layout x and y for each node (person)" was calculated by py2mappr?

please see above.

**Comment by ericberlow** [comment]
in `network_functions.py` you can find some functions to add force-directed layout and t-sne layout coordinates

**Comment by ericberlow** [comment]
`build_openmappr_files.py` has simple functions to convert your excel sheet into the 3 csv's

**Comment by retorquere** [comment]
Ah -- networkx does the x/y calc. Gotcha.

**Comment by ericberlow** [comment]
`create_TED_map.py` has the example for creating snapshots and styling for the TED talks map.  There is also another example of a directed network called 'digital_delta' - `build_dd_player.py`

**Comment by ericberlow** [comment]
> Ah -- networkx does the x/y calc. Gotcha.

yes! we didn't want to reinvent the wheel with py2mappr and create another network analysis module - but rather focus on the problem of highly interactive network visualization  - all networkx network viz is static and not very pretty...

**Comment by retorquere** [comment]
So the order is:

* generate source xlsx
* run that through `network_functions` somehow to generate x/y
* run the results of that through `build_openmappr_files.py` to build the 3 `.csv`s
* ???
* profit

?

**Comment by ericberlow** [comment]
> So the order is:
> 
> * generate source xlsx
> * run that through `network_functions` somehow to generate x/y
> * run the results of that through `build_openmappr_files.py` to build the 3 `.csv`s
> * ???
> * profit
> 
> ?

yes. 

Here is the flow:
- generate excel with 2 sheets - nodes and links
- add metadata to the nodes - which includes: network metrics (computed with networkx), network layout coordinates (computed with networkx), any other custom node attributes you want to use for coloring, sizing, spatial positioning, filtering/selecting.
- convert the excel sheet into: nodes.csv, links.csv, node_attributes.csv.  The latter just transposes all the column headers from the nodes file into rows - and then the columns are settings for what type of data is it (e.g. string, integer, date etc), and how it should be visually rendered (e.g. histogram, tags, wide tags), and whether it should be visible or hidden, etc. 
- create player settings -  create 'snapshots', for each snapshot specify what type of layout, the coordinates of the layout, style settings for node and link colors, sizes, interactivity options, etc. ; then what is the order of the snapshots; snapshot descriptions, etc.  
- write the player files to an out put folder
- load the player locally in the browser or upload it to a static web server
- profit :)

**Comment by ericberlow** [comment]
I'm going offline now - will be available tomorrow PT

**Comment by retorquere** [comment]
No need to answer these immediately, but:

> * add metadata to the nodes - which includes: network metrics (computed with networkx), network layout coordinates (computed with networkx), any other custom node attributes you want to use for coloring, sizing, spatial positioning, filtering/selecting.
> * convert the excel sheet into: nodes.csv, links.csv, node_attributes.csv. The latter just transposes all the column headers from the nodes file into rows - and then the columns are settings for what type of data is it (e.g. string, integer, date etc), and how it should be visually rendered (e.g. histogram, tags, wide tags), and whether it should be visible or hidden, etc.
> * create player settings - create 'snapshots', for each snapshot specify what type of layout, the coordinates of the layout, style settings for node and link colors, sizes, interactivity options, etc. ; then what is the order of the snapshots; snapshot descriptions, etc.

I don't know for each of these steps whether it is done by running one of the existing python scripts in the repo, or whether I should create my own script based on one of the scripts in the repo and run that, and which the relevant scripts are.

When I try to run `prepare_data.py` from the TED demo I'm getting:

```
$ python3 prepare_data.py 
Traceback (most recent call last):
  File "/Users/emile/github/py2mappr/projects/public/TED_talks_demo/prepare_data.py", line 13, in <module>
    from Network import BuildNetwork as bn
ImportError: cannot import name 'BuildNetwork' from 'Network' (unknown location)
```

and there's no file in the repo that has the class or function `BuildNetwork`

**Comment by ericberlow** [comment]
> No need to answer these immediately, but:
> 
> > * add metadata to the nodes - which includes: network metrics (computed with networkx), network layout coordinates (computed with networkx), any other custom node attributes you want to use for coloring, sizing, spatial positioning, filtering/selecting.
> > * convert the excel sheet into: nodes.csv, links.csv, node_attributes.csv. The latter just transposes all the column headers from the nodes file into rows - and then the columns are settings for what type of data is it (e.g. string, integer, date etc), and how it should be visually rendered (e.g. histogram, tags, wide tags), and whether it should be visible or hidden, etc.
> > * create player settings - create 'snapshots', for each snapshot specify what type of layout, the coordinates of the layout, style settings for node and link colors, sizes, interactivity options, etc. ; then what is the order of the snapshots; snapshot descriptions, etc.
> 
> I don't know for each of these steps whether it is done by running one of the existing python scripts in the repo, or whether I should create my own script based on one of the scripts in the repo and run that, and which the relevant scripts are.

- adding metadata to nodes - best done outside py2mappr - i have a few functions in there i use, but they are not yet well refactored to avoid local dependencies.  They are all based on networkx, pandas etc. 
- converting excel sheet to openmappr input files - there is a function in py2mappr `build_openmappr_files.py` called `write_openmappr_files` - this is a work in progress, but will generate the node_attributes.csv file and auto-populate the rendering settings. You can then edit them manually, or add custom lists of column headers of different types to customize their settings. 
- build the player - this is the main goal of py2mappr - in `map_utils` there are two functions `create_snapshot` and `create_map`  - the demo scripts  `create_TED_map.py` and `build_dd_player.py` have examples of how to create snapshots and create the map.  

> 
> When I try to run `prepare_data.py` from the TED demo I'm getting:
> 
> ```
> $ python3 prepare_data.py 
> Traceback (most recent call last):
>   File "/Users/emile/github/py2mappr/projects/public/TED_talks_demo/prepare_data.py", line 13, in <module>
>     from Network import BuildNetwork as bn
> ImportError: cannot import name 'BuildNetwork' from 'Network' (unknown location)
> ```
> 
> and there's no file in the repo that has the class or function `BuildNetwork`

- Sorry - this prepare_data script was essentially pre-processing the data to add node metadata, etc.  It has some local dependencies - BuildNetwork comes from https://github.com/foodwebster/tag2network - which is cloned on my machine in a 'Github' directory.  It has some network functions that I use - and is the repo for generating affinity networks.   It is not required.  You should be able to generate what you want with other python libraries (networkx, etc). 

Again - my apologies this is not more transparent - we literally just got py2mappr working a few months ago - I am the only one who has been using it, and we have not had any resources to refactor the code, document, etc and make it easy to import.   For example, currently, you have to copy the entire directory `src/templates/` into your local directory to import the default settings etc.   I have some resources dedicating to cleaning this up on a project that is due end of October.

**Comment by retorquere** [comment]
How did you get it to work at all? How did you get familiar with what openmappr needs?

**Comment by ericberlow** [comment]
> How did you get it to work at all? How did you get familiar with what openmappr needs?

ha. I literally just made a map for another project 5 minutes ago.   :). 
Long story. We build mappr as part of our startup company -  it was the full browser based tool where you upload a spreadsheet to an editor, style your network, add snapshots etc, and then publish the player.  I was the science co-founder, and kaustuv debiswas was the technical/product co-founder (there was a third co-founder who was art/design).   We bootstrapped mappr without any investment - and were acquired before really finishing a user-friendly version.  The company that acquired us let us open source it >> and I forked a branck >> openmappr - then Kaustuv helped me remove the browser based editor and directly publish players from python (py2mappr).   What you see here is the very first v.0.0 prototype. It works great actually for my needs, but needs alot of work to make it easily useable by others.    That's why I suggested that if you just send me the processed network file - excel file with nodes sheet and links sheet - where the nodes have all the metadata you need (network metrics, custom columns for sizing, coloring filtering, descriptions, etc), then I can create a clean script for you that generates openmappr files, builds snapshots, builds the player, publishes the player, etc.   Then you can edit easily.    I think that would take less time for both of us than you bumping into questions and me answering them here.   I would be thrilled to get a clean pipeline for you to convert zotero data to interactive networks if we can get it running.

**Comment by ericberlow** [comment]
@Jack-613    - thinking about your project - I think in the end it may be more useful to you to have a network where the nodes are documents and they are linked if they share authors - rather than a network of nodes = people, linked if they were co-authors.   The former will allow you to browse your entire library in openmappr - clicking on a node would reveal the title, authors, year, journal, abstract, tags - and the filters panel would allow you to select nodes (papers) by author, journal, year, tags etc.         

@retorquere that would just require that you flip the network so nodes are documents with unique document id;  
Nodes sheet would have columns: document id, author list (separated by "|"), title, abstract, journal, tags (separated by "|"), etc.
Links sheet has: source document, target document, weight (# authors they share) 

If you do this, I can help you decorate it with node metadata and create a clean script for turning it in to an openplayer network.   It will just require a little patience on your end for me to get to over the next month.  But it will be much more efficient than trying to hash out every little confusing thing here.  

Let me know what you think.

**Comment by retorquere** [comment]
> that would just require that you flip the network so nodes are documents with unique document id;
> Nodes sheet would have columns: document id, author list (separated by "|"), title, abstract, journal, tags (separated by "|"), etc.
> Links sheet has: source document, target document, weight (# authors they share)

Where source and target means that they are documents that share at least one author, correct?

**Comment by ericberlow** [comment]
> > that would just require that you flip the network so nodes are documents with unique document id;
> > Nodes sheet would have columns: document id, author list (separated by "|"), title, abstract, journal, tags (separated by "|"), etc.
> > Links sheet has: source document, target document, weight (# authors they share)
> 
> Where source and target means that they are documents that share at least one author, correct?

exactly.

**Comment by retorquere** [comment]
@Jack-613 before I embark on this, is this what you are looking for?

**Comment by retorquere** [comment]
This should be it
[Exported Items.xlsx](https://github.com/ericberlow/py2mappr/files/6910224/Exported.Items.xlsx)

**Comment by ericberlow** [comment]
> This should be it
> [Exported Items.xlsx](https://github.com/ericberlow/py2mappr/files/6910224/Exported.Items.xlsx)

looks great.  but  in the nodes sheet:  abstract and journal columns are empty.  would also be good to add publication year?  then you can select or sort by year.  
Also i can see that the tags have some inconsistencies - sometimes there is "*" prefix, sometimes not;  sometimes capitalized sometimes not.  I can process on my end, but just thought I'd point it out.

**Comment by retorquere** [comment]
[Exported Items.xlsx](https://github.com/ericberlow/py2mappr/files/6910312/Exported.Items.xlsx)

> Also i can see that the tags have some inconsistencies - sometimes there is "*" prefix, sometimes not; sometimes capitalized sometimes not. I can process on my end, but just thought I'd point it out.

That's just what is in Jakob's library.
